environment:
  matrix:
    - nodejs_version: "9"

install:
- ps: Install-Product node $env:nodejs_version
- npm install
- npm install -g gulp
- npm install -g mocha

test_script:
- node --version
- npm --version
- npm run test

build_script:
- cmd: gulp

cache:
- node_modules
